/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package compositeControl.validation;

import compositeControl.CompositeControl;

/**
 * A sample validator interface for {@link compositeControl.Seq}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SeqValidator {
	boolean validate();

	boolean validateLeftBranch(CompositeControl value);
	boolean validateRightBranch(CompositeControl value);
}
