package org.eventb.codegen.taskbodybuilder;
/* Generated By:JavaCC: Do not edit this line. TaskingGrammarConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TaskingGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SEQ = 5;
  /** RegularExpression Id. */
  int IF = 6;
  /** RegularExpression Id. */
  int ELSEIF = 7;
  /** RegularExpression Id. */
  int ELSE = 8;
  /** RegularExpression Id. */
  int DO = 9;
  /** RegularExpression Id. */
  int FINALLY = 10;
  /** RegularExpression Id. */
  int OUTPUT = 11;
  /** RegularExpression Id. */
  int NAME = 12;
  /** RegularExpression Id. */
  int NAMECHAR = 13;
  /** RegularExpression Id. */
  int STRING = 14;
  /** RegularExpression Id. */
  int ASCII = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\";\"",
    "\"if\"",
    "\"elseif\"",
    "\"else\"",
    "\"do\"",
    "\"finally\"",
    "\"output\"",
    "<NAME>",
    "<NAMECHAR>",
    "<STRING>",
    "<ASCII>",
    "\"(\"",
    "\")\"",
  };

}
